---
bibliography: references.bib
---

# Principles of effective communication of research

## Knowledge mobilization plan

The (not so) simple act of completing a research project does not guarantee that it will reach its potential outcomes. For this to happen, your work needs to reach the places where and the people for who it can have an impact. The purpose of the knowledge mobilization plan is to provide details on the different **outputs** (e.g., research article, policy brief, blog post, podcast) and **events** (e.g., round table, seminar, workshop) that you will produce, organize, or take part to reach your **audiences** (e.g., your peers, researchers in other fields, practitioners, policymakers, members of the public, etc.)**.** As much as possible and relevant, your knowledge mobilization plan should provide details on the specific **channels** that you will use to share your outputs (e.g., what journal specifically, which blog platform, what conference, etc.).

You should also make sure to clearly link outputs, activities and audiences in your plan. This means that you should avoid providing a list of audiences, a list of outputs, and a list of activities one after the other. Instead, describe different startegies/activities that each include one or multiple specific target audiences, outputs and/or activities.

Finally, you should make sure to provide, when possible, a **succint** justification for your choices. Think of this as the why? Why is this an important audience, why are these the best output format and channels to reach them?

## Expected outcomes

The goal of the expected outcomes section is Describe the potential benefits and outcomes (e.g., evolution, effects, potential learning and implications) that could emerge from the proposed project as a result of knowledge mobilization activities.

The research outcomes section is about the potential impact of your research. What changes could it bring into the world? What problem might it help resolved? Who's lives might be improved and it what way?

Here is a exceprt from the instructions provided by the Social Science and Humanities Research Council of Canada (SSHRC) for the Insight Grants program:

> Research and related outcomes include enhanced curriculum and teaching material, enriched public discourse, improved public policies, enhanced business strategies and increased innovations in every sector of society, as well as graduate supervision opportunities. Research outcomes, which are facilitated by the effective mobilization of knowledge, then permeate daily life in the form of new thinking and behaviour that lead to improvements in our economic, social, cultural and intellectual well-being. ([SSRCH](https://www.sshrc-crsh.gc.ca/funding-financement/instructions/ig-ss/applicant-candidat-eng.aspx#outcomes-resultats)).

No research is actually going to fix the whole problem. Still, every little bit of knowledge can contribute in a small way. So here you don't want to limit yourself to the outcomes that are measurable or significant, but also include the ways in which your research will help in a small way. That said, you also don't want to make exaggerated, grandiose claims (e.g., my research will elimitate world hunger, my research will elimitate taxes, my research will provide a cure for human stupidity).
