# Overview {.unnumbered}

This book is a work-in-progress intended to support the course INFO5520 - Research Methods offered in the Master of Information program at Dalhousie University.

::: callout-important
## Important note

Winter 2025 will be the first iteration of this new version of the course, which means that:

-   Most content is not yet available and will be uploaded over the course of the semester.
-   Depending on time constraints, some chapters may end up being very briefs, or include only a set of slides used for in-class presentations.

Thank you for your understanding!
:::

::: callout-note
This book can be accessed directly from your browser (without going through Brightspace) using the following URL: <https://pmongeon.github.io/info5520/>
:::

## Schedule

| Week | Section | Topic |
|:--:|----|----|
| 1 | Introduction | Course overview, key concepts in research |
| 2 | Conceptual phase | Literature review |
| 3 | Conceptual phase | Research problems, purpose, and questions |
| 4 | Methodological phase | Methodological designs, research ethics |
| 5 | Methodological phase | Sampling |
| 6 | Methodological phase | Defining, operationalizing and measuring concepts |
| 7 | Methodological phase | Qualitative data collection |
| 8 | Methodological phase | Quantitative data collection |
| 9 | Analytical phase | Qualitative data analysis |
| 10 | Analytical phase | Descriptive and inferential statistics |
| 11 | Reporting phase | Principle of effective written, visual and oral presentation of research. |
| 12 | Reporting phase | Group presentations |

::: callout-important
Use the course Brightspace to:

-   Access the syllabus (under the content - overview tab).
-   Access the assignments instructions and due dates.
-   Submit your assignments.
:::

## Other information and resources

-   Use APA style for your references in all assignments.

-   Use [Zotero](https://www.zotero.org) (or another reference manager of your choice) to store your references and to cite them in your work. (not mandatory, but highly recommended).

-   You can use this [Word template](files/assignment-template.dotx) to write your assignments (not mandatory). Whether you use this template or not, use Word styles to format and structure your document.

-   Have fun.
